import { assignColorsToCategories } from "./colors";

export const categories = {
  income: assignColorsToCategories([
    { label: "Freelance", value: "freelance" },
    { label: "Otros ingresos", value: "otros-ingresos" },
    { label: "Salario", value: "salario" },
  ]),
  savings: assignColorsToCategories([
    { label: "Ahorros", value: "ahorros" },
    { label: "Inversiones", value: "inversiones" },
  ]),
  expense: assignColorsToCategories([
    { label: "Actividad física", value: "actividad-fisica" },
    { label: "Alquiler", value: "alquiler" },
    { label: "Celulares", value: "celulares" },
    { label: "Círculo", value: "circulo" },
    { label: "Combustible", value: "combustible" },
    { label: "Comida", value: "comida" },
    { label: "Compras", value: "compras" },
    { label: "Dibujo", value: "dibujo" },
    { label: "Disney+", value: "disney-plus" },
    { label: "Educación", value: "educacion" },
    { label: "Hobbies", value: "hobbies" },
    { label: "Internet", value: "internet" },
    { label: "Netflix", value: "netflix" },
    { label: "Otros gastos", value: "otros-gastos" },
    { label: "Préstamos", value: "prestamos" },
    { label: "Regalos", value: "regalos" },
    { label: "Salidas", value: "salidas" },
    { label: "Salud", value: "salud" },
    { label: "Servicios (Luz, Gas, Agua)", value: "servicios" },
    { label: "Spotify", value: "spotify" },
    { label: "Supermercado", value: "supermercado" },
    { label: "Tarjeta de crédito", value: "tarjeta-credito" },
    { label: "Transferencias", value: "transferencias" },
    { label: "Transporte", value: "transporte" },
    { label: "YouTube Premium", value: "youtube-premium" },
  ]),
};